# Новый порт
server.port=8081

# Настройки подключения к PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/clientdb
spring.datasource.username=postgres
spring.datasource.password=123454321

# Hibernate настройки
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
